# Generated by Django 6.0.5 on 2026-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('size_sqft', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('lift', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('balcony', models.IntegerField(default=0)),
            ],
        ),
    ]
